// Этот файл теперь хранит все глаголы.
// Если вы захотите добавить новые, вы будете редактировать только этот файл.
// Добавлено поле type для указания типа глагола: "weak" (слабый), "strong" (сильный), "mixed" (смешанный), "modal" (модальный), "irregular" (особый/неправильный), "regular" (правильный).
// Если тип неочевиден, используйте "regular" для правильных, "irregular" для неправильных, "modal" для модальных.

export const allVerbs = [
  // A1
  {
    infinitive: "sein",
    russian: "быть",
    level: "A1",
    type: "irregular",
    forms: ["bin", "bist", "ist", "sind", "seid", "sind"],
  },
  {
    infinitive: "haben",
    russian: "иметь",
    level: "A1",
    type: "irregular",
    forms: ["habe", "hast", "hat", "haben", "habt", "haben"],
  },
  {
    infinitive: "werden",
    russian: "становиться",
    level: "A1",
    type: "irregular",
    forms: ["werde", "wirst", "wird", "werden", "werdet", "werden"],
  },
  {
    infinitive: "können",
    russian: "мочь",
    level: "A1",
    type: "modal",
    forms: ["kann", "kannst", "kann", "können", "könnt", "können"],
  },
  {
    infinitive: "müssen",
    russian: "быть должным",
    level: "A1",
    type: "modal",
    forms: ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
  },
  {
    infinitive: "wollen",
    russian: "хотеть",
    level: "A1",
    type: "modal",
    forms: ["will", "willst", "will", "wollen", "wollt", "wollen"],
  },
  {
    infinitive: "sagen",
    russian: "сказать",
    level: "A1",
    type: "weak",
    forms: ["sage", "sagst", "sagt", "sagen", "sagt", "sagen"],
  },
  {
    infinitive: "machen",
    russian: "делать",
    level: "A1",
    type: "weak",
    forms: ["mache", "machst", "macht", "machen", "macht", "machen"],
  },
  {
    infinitive: "geben",
    russian: "давать",
    level: "A1",
    type: "strong",
    forms: ["gebe", "gibst", "gibt", "geben", "gebt", "geben"],
  },
  {
    infinitive: "kommen",
    russian: "приходить",
    level: "A1",
    type: "strong",
    forms: ["komme", "kommst", "kommt", "kommen", "kommt", "kommen"],
  },
  {
    infinitive: "gehen",
    russian: "идти",
    level: "A1",
    type: "strong",
    forms: ["gehe", "gehst", "geht", "gehen", "geht", "gehen"],
  },
  {
    infinitive: "wissen",
    russian: "знать",
    level: "A1",
    type: "irregular",
    forms: ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
  },
  {
    infinitive: "sehen",
    russian: "видеть",
    level: "A1",
    type: "strong",
    forms: ["sehe", "siehst", "sieht", "sehen", "seht", "sehen"],
  },
  {
    infinitive: "finden",
    russian: "находить",
    level: "A1",
    type: "strong",
    forms: ["finde", "findest", "findet", "finden", "findet", "finden"],
  },
  {
    infinitive: "bleiben",
    russian: "оставаться",
    level: "A1",
    type: "strong",
    forms: ["bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"],
  },
  {
    infinitive: "heißen",
    russian: "называться",
    level: "A1",
    type: "weak",
    forms: ["heiße", "heißt", "heißt", "heißen", "heißt", "heißen"],
  },
  {
    infinitive: "denken",
    russian: "думать",
    level: "A1",
    type: "mixed",
    forms: ["denke", "denkst", "denkt", "denken", "denkt", "denken"],
  },
  {
    infinitive: "nehmen",
    russian: "брать",
    level: "A1",
    type: "strong",
    forms: ["nehme", "nimmst", "nimmt", "nehmen", "nehmt", "nehmen"],
  },
  {
    infinitive: "tun",
    russian: "делать",
    level: "irregular",
    type: "irregular",
    forms: ["tue", "tust", "tut", "tun", "tut", "tun"],
  },
  {
    infinitive: "sprechen",
    russian: "говорить",
    level: "A1",
    type: "strong",
    forms: [
      "spreche",
      "sprichst",
      "spricht",
      "sprechen",
      "sprecht",
      "sprechen",
    ],
  },
  {
    infinitive: "fahren",
    russian: "ехать",
    level: "A1",
    type: "strong",
    forms: ["fahre", "fährst", "fährt", "fahren", "fahrt", "fahren"],
  },
  {
    infinitive: "fragen",
    russian: "спрашивать",
    level: "A1",
    type: "weak",
    forms: ["frage", "fragst", "fragt", "fragen", "fragt", "fragen"],
  },
  {
    infinitive: "arbeiten",
    russian: "работать",
    level: "A1",
    type: "weak",
    forms: [
      "arbeite",
      "arbeitest",
      "arbeitet",
      "arbeiten",
      "arbeitet",
      "arbeiten",
    ],
  },
  {
    infinitive: "brauchen",
    russian: "нуждаться",
    level: "A1",
    type: "weak",
    forms: [
      "brauche",
      "brauchst",
      "braucht",
      "brauchen",
      "braucht",
      "brauchen",
    ],
  },
  {
    infinitive: "glauben",
    russian: "верить",
    level: "A1",
    type: "weak",
    forms: ["glaube", "glaubst", "glaubt", "glauben", "glaubt", "glauben"],
  },
  {
    infinitive: "helfen",
    russian: "помогать",
    level: "A1",
    type: "strong",
    forms: ["helfe", "hilfst", "hilft", "helfen", "helft", "helfen"],
  },
  {
    infinitive: "kaufen",
    russian: "покупать",
    level: "A1",
    type: "weak",
    forms: ["kaufe", "kaufst", "kauft", "kaufen", "kauft", "kaufen"],
  },
  {
    infinitive: "kochen",
    russian: "готовить",
    level: "A1",
    type: "weak",
    forms: ["koche", "kochst", "kocht", "kochen", "kocht", "kochen"],
  },
  {
    infinitive: "lernen",
    russian: "учиться",
    level: "A1",
    type: "weak",
    forms: ["lerne", "lernst", "lernt", "lernen", "lernt", "lernen"],
  },
  {
    infinitive: "lesen",
    russian: "читать",
    level: "A1",
    type: "strong",
    forms: ["lese", "liest", "liest", "lesen", "lest", "lesen"],
  },
  {
    infinitive: "leben",
    russian: "жить",
    level: "A1",
    type: "weak",
    forms: ["lebe", "lebst", "lebt", "leben", "lebt", "leben"],
  },
  {
    infinitive: "lieben",
    russian: "любить",
    level: "A1",
    type: "weak",
    forms: ["liebe", "liebst", "liebt", "lieben", "liebt", "lieben"],
  },
  {
    infinitive: "öffnen",
    russian: "открывать",
    level: "A1",
    type: "weak",
    forms: ["öffne", "öffnest", "öffnet", "öffnen", "öffnet", "öffnen"],
  },
  {
    infinitive: "schlafen",
    russian: "спать",
    level: "A1",
    type: "strong",
    forms: [
      "schlafe",
      "schläfst",
      "schläft",
      "schlafen",
      "schlaft",
      "schlafen",
    ],
  },
  {
    infinitive: "schließen",
    russian: "закрывать",
    level: "A1",
    type: "weak",
    forms: [
      "schließe",
      "schließt",
      "schließt",
      "schließen",
      "schließt",
      "schließen",
    ],
  },
  {
    infinitive: "schreiben",
    russian: "писать",
    level: "A1",
    type: "strong",
    forms: [
      "schreibe",
      "schreibst",
      "schreibt",
      "schreiben",
      "schreibt",
      "schreiben",
    ],
  },
  {
    infinitive: "sitzen",
    russian: "сидеть",
    level: "A1",
    type: "strong",
    forms: ["sitze", "sitzt", "sitzt", "sitzen", "sitzt", "sitzen"],
  },
  {
    infinitive: "spielen",
    russian: "играть",
    level: "A1",
    type: "weak",
    forms: ["spiele", "spielst", "spielt", "spielen", "spielt", "spielen"],
  },
  {
    infinitive: "stehen",
    russian: "стоять",
    level: "A1",
    type: "strong",
    forms: ["stehe", "stehst", "steht", "stehen", "steht", "stehen"],
  },
  {
    infinitive: "suchen",
    russian: "искать",
    level: "A1",
    type: "weak",
    forms: ["suche", "suchst", "sucht", "suchen", "sucht", "suchen"],
  },
  {
    infinitive: "tanzen",
    russian: "танцевать",
    level: "A1",
    type: "weak",
    forms: ["tanze", "tanzt", "tanzt", "tanzen", "tanzt", "tanzen"],
  },
  {
    infinitive: "trinken",
    russian: "пить",
    level: "A1",
    type: "strong",
    forms: ["trinke", "trinkst", "trinkt", "trinken", "trinkt", "trinken"],
  },
  {
    infinitive: "verkaufen",
    russian: "продавать",
    level: "A1",
    type: "weak",
    forms: [
      "verkaufe",
      "verkaufst",
      "verkauft",
      "verkaufen",
      "verkauft",
      "verkaufen",
    ],
  },
  {
    infinitive: "wohnen",
    russian: "проживать",
    level: "A1",
    type: "weak",
    forms: ["wohne", "wohnst", "wohnt", "wohnen", "wohnt", "wohnen"],
  },
  {
    infinitive: "zeigen",
    russian: "показывать",
    level: "A1",
    type: "weak",
    forms: ["zeige", "zeigst", "zeigt", "zeigen", "zeigt", "zeigen"],
  },
  // A2
  {
    infinitive: "anrufen",
    russian: "звонить по телефону",
    level: "A2",
    type: "separable",
    forms: [
      "rufe an",
      "rufst an",
      "ruft an",
      "rufen an",
      "ruft an",
      "rufen an",
    ],
  },
  {
    infinitive: "antworten",
    russian: "отвечать",
    level: "A2",
    type: "weak",
    forms: [
      "antworte",
      "antwortest",
      "antwortet",
      "antworten",
      "antwortet",
      "antworten",
    ],
  },
  {
    infinitive: "aussehen",
    russian: "выглядеть",
    level: "A2",
    type: "separable",
    forms: [
      "sehe aus",
      "siehst aus",
      "sieht aus",
      "sehen aus",
      "seht aus",
      "sehen aus",
    ],
  },
  {
    infinitive: "beginnen",
    russian: "начинать",
    level: "A2",
    type: "strong",
    forms: [
      "beginne",
      "beginnst",
      "beginnt",
      "beginnen",
      "beginnt",
      "beginnen",
    ],
  },
  {
    infinitive: "bekommen",
    russian: "получать",
    level: "A2",
    type: "irregular",
    forms: [
      "bekomme",
      "bekommst",
      "bekommt",
      "bekommen",
      "bekommt",
      "bekommen",
    ],
  },
  {
    infinitive: "bestellen",
    russian: "заказывать",
    level: "A2",
    type: "weak",
    forms: [
      "bestelle",
      "bestellst",
      "bestellt",
      "bestellen",
      "bestellt",
      "bestellen",
    ],
  },
  {
    infinitive: "bezahlen",
    russian: "платить",
    level: "A2",
    type: "weak",
    forms: [
      "bezahle",
      "bezahlst",
      "bezahlt",
      "bezahlen",
      "bezahlt",
      "bezahlen",
    ],
  },
  {
    infinitive: "bitten",
    russian: "просить",
    level: "A2",
    type: "irregular",
    forms: ["bitte", "bittest", "bittet", "bitten", "bittet", "bitten"],
  },
  {
    infinitive: "danken",
    russian: "благодарить",
    level: "A2",
    type: "weak",
    forms: ["danke", "dankst", "dankt", "danken", "dankt", "danken"],
  },
  {
    infinitive: "einladen",
    russian: "приглашать",
    level: "A2",
    type: "separable",
    forms: [
      "lade ein",
      "lädst ein",
      "lädt ein",
      "laden ein",
      "ladet ein",
      "laden ein",
    ],
  },
  {
    infinitive: "erklären",
    russian: "объяснять",
    level: "A2",
    type: "weak",
    forms: [
      "erkläre",
      "erklärst",
      "erklärt",
      "erklären",
      "erklärt",
      "erklären",
    ],
  },
  {
    infinitive: "erzählen",
    russian: "рассказывать",
    level: "A2",
    type: "weak",
    forms: [
      "erzähle",
      "erzählst",
      "erzählt",
      "erzählen",
      "erzählt",
      "erzählen",
    ],
  },
  {
    infinitive: "essen",
    russian: "есть, кушать",
    level: "A2",
    type: "strong",
    forms: ["esse", "isst", "isst", "essen", "esst", "essen"],
  },
  {
    infinitive: "feiern",
    russian: "праздновать",
    level: "A2",
    type: "weak",
    forms: ["feiere", "feierst", "feiert", "feiern", "feiert", "feiern"],
  },
  {
    infinitive: "fliegen",
    russian: "летать",
    level: "A2",
    type: "strong",
    forms: ["fliege", "fliegst", "fliegt", "fliegen", "fliegt", "fliegen"],
  },
  {
    infinitive: "gefallen",
    russian: "нравиться",
    level: "A2",
    type: "strong",
    forms: [
      "gefalle",
      "gefällst",
      "gefällt",
      "gefallen",
      "gefallt",
      "gefallen",
    ],
  },
  {
    infinitive: "gehören",
    russian: "принадлежать",
    level: "A2",
    type: "weak",
    forms: ["gehöre", "gehörst", "gehört", "gehören", "gehört", "gehören"],
  },
  {
    infinitive: "gewinnen",
    russian: "выигрывать",
    level: "A2",
    type: "strong",
    forms: [
      "gewinne",
      "gewinnst",
      "gewinnt",
      "gewinnen",
      "gewinnt",
      "gewinnen",
    ],
  },
  {
    infinitive: "hoffen",
    russian: "надеяться",
    level: "A2",
    type: "weak",
    forms: ["hoffe", "hoffst", "hofft", "hoffen", "hofft", "hoffen"],
  },
  {
    infinitive: "kennenlernen",
    russian: "знакомиться",
    level: "A2",
    type: "separable",
    forms: [
      "lerne kennen",
      "lernst kennen",
      "lernt kennen",
      "lernen kennen",
      "lernt kennen",
      "lernen kennen",
    ],
  },
  {
    infinitive: "lachen",
    russian: "смеяться",
    level: "A2",
    type: "weak",
    forms: ["lache", "lachst", "lacht", "lachen", "lacht", "lachen"],
  },
  {
    infinitive: "laufen",
    russian: "бежать",
    level: "A2",
    type: "strong",
    forms: ["laufe", "läufst", "läuft", "laufen", "lauft", "laufen"],
  },
  {
    infinitive: "reisen",
    russian: "путешествовать",
    level: "A2",
    type: "weak",
    forms: ["reise", "reist", "reist", "reisen", "reist", "reisen"],
  },
  {
    infinitive: "reservieren",
    russian: "резервировать",
    level: "A2",
    type: "weak",
    forms: [
      "reserviere",
      "reservierst",
      "reserviert",
      "reservieren",
      "reserviert",
      "reservieren",
    ],
  },
  {
    infinitive: "schenken",
    russian: "дарить",
    level: "A2",
    type: "weak",
    forms: [
      "schenke",
      "schenkst",
      "schenkt",
      "schenken",
      "schenkt",
      "schenken",
    ],
  },
  {
    infinitive: "tragen",
    russian: "носить",
    level: "A2",
    type: "strong",
    forms: ["trage", "trägst", "trägt", "tragen", "tragt", "tragen"],
  },
  {
    infinitive: "treffen",
    russian: "встречать",
    level: "A2",
    type: "strong",
    forms: ["treffe", "triffst", "trifft", "treffen", "trefft", "treffen"],
  },
  {
    infinitive: "vergessen",
    russian: "забывать",
    level: "A2",
    type: "strong",
    forms: [
      "vergesse",
      "vergisst",
      "vergisst",
      "vergessen",
      "vergesst",
      "vergessen",
    ],
  },
  {
    infinitive: "verlieren",
    russian: "терять",
    level: "A2",
    type: "strong",
    forms: [
      "verliere",
      "verlierst",
      "verliert",
      "verlieren",
      "verliert",
      "verlieren",
    ],
  },
  {
    infinitive: "verstehen",
    russian: "понимать",
    level: "A2",
    type: "strong",
    forms: [
      "verstehe",
      "verstehst",
      "versteht",
      "verstehen",
      "versteht",
      "verstehen",
    ],
  },
  {
    infinitive: "vorbereiten",
    russian: "готовиться",
    level: "A2",
    type: "separable",
    forms: [
      "bereite vor",
      "bereitest vor",
      "bereitet vor",
      "bereiten vor",
      "bereitet vor",
      "bereiten vor",
    ],
  },
  {
    infinitive: "warten",
    russian: "ждать",
    level: "A2",
    type: "weak",
    forms: ["warte", "wartest", "wartet", "warten", "wartet", "warten"],
  },
  {
    infinitive: "waschen",
    russian: "мыть",
    level: "A2",
    type: "strong",
    forms: ["wasche", "wäschst", "wäscht", "waschen", "wascht", "waschen"],
  },
  {
    infinitive: "wünschen",
    russian: "желать",
    level: "A2",
    type: "weak",
    forms: [
      "wünsche",
      "wünschst",
      "wünscht",
      "wünschen",
      "wünscht",
      "wünschen",
    ],
  },
  {
    infinitive: "ziehen",
    russian: "тянуть, переезжать",
    level: "A2",
    type: "strong",
    forms: ["ziehe", "ziehst", "zieht", "ziehen", "zieht", "ziehen"],
  },
  // B1
  {
    infinitive: "abhängen",
    russian: "зависеть",
    level: "B1",
    type: "separable",
    forms: [
      "hänge ab",
      "hängst ab",
      "hängt ab",
      "hängen ab",
      "hängt ab",
      "hängen ab",
    ],
  },
  {
    infinitive: "ändern",
    russian: "менять",
    level: "B1",
    type: "weak",
    forms: ["ändere", "änderst", "ändert", "ändern", "ändert", "ändern"],
  },
  {
    infinitive: "anbieten",
    russian: "предлагать",
    level: "B1",
    type: "separable",
    forms: [
      "biete an",
      "bietest an",
      "bietet an",
      "bieten an",
      "bietet an",
      "bieten an",
    ],
  },
  {
    infinitive: "annehmen",
    russian: "принимать",
    level: "B1",
    type: "separable",
    forms: [
      "nehme an",
      "nimmst an",
      "nimmt an",
      "nehmen an",
      "nehmt an",
      "nehmen an",
    ],
  },
  {
    infinitive: "atmen",
    russian: "дышать",
    level: "B1",
    type: "weak",
    forms: ["atme", "atmest", "atmet", "atmen", "atmet", "atmen"],
  },
  {
    infinitive: "aufgeben",
    russian: "сдаваться",
    level: "B1",
    type: "separable",
    forms: [
      "gebe auf",
      "gibst auf",
      "gibt auf",
      "geben auf",
      "gebt auf",
      "geben auf",
    ],
  },
  {
    infinitive: "ausgeben",
    russian: "тратить",
    level: "B1",
    type: "separable",
    forms: [
      "gebe aus",
      "gibst aus",
      "gibt aus",
      "geben aus",
      "gebt aus",
      "geben aus",
    ],
  },
  {
    infinitive: "bedeuten",
    russian: "означать",
    level: "B1",
    type: "weak",
    forms: [
      "bedeute",
      "bedeutest",
      "bedeutet",
      "bedeuten",
      "bedeutet",
      "bedeuten",
    ],
  },
  {
    infinitive: "benutzen",
    russian: "использовать",
    level: "B1",
    type: "weak",
    forms: ["benutze", "benutzt", "benutzt", "benutzen", "benutzt", "benutzen"],
  },
  {
    infinitive: "beraten",
    russian: "советовать",
    level: "B1",
    type: "strong",
    forms: ["berate", "berätst", "berät", "beraten", "beratet", "beraten"],
  },
  {
    infinitive: "entscheiden",
    russian: "решать",
    level: "B1",
    type: "strong",
    forms: [
      "entscheide",
      "entscheidest",
      "entscheidet",
      "entscheiden",
      "entscheidet",
      "entscheiden",
    ],
  },
  {
    infinitive: "entwickeln",
    russian: "развивать",
    level: "B1",
    type: "weak",
    forms: [
      "entwickle",
      "entwickelst",
      "entwickelt",
      "entwickeln",
      "entwickelt",
      "entwickeln",
    ],
  },
  {
    infinitive: "erinnern",
    russian: "помнить",
    level: "B1",
    type: "weak",
    forms: [
      "erinnere",
      "erinnerst",
      "erinnert",
      "erinnern",
      "erinnert",
      "erinnern",
    ],
  },
  {
    infinitive: "erkennen",
    russian: "узнавать",
    level: "B1",
    type: "irregular",
    forms: [
      "erkenne",
      "erkennst",
      "erkennt",
      "erkennen",
      "erkennt",
      "erkennen",
    ],
  },
  {
    infinitive: "erlauben",
    russian: "разрешать",
    level: "B1",
    type: "weak",
    forms: [
      "erlaube",
      "erlaubst",
      "erlaubt",
      "erlauben",
      "erlaubt",
      "erlauben",
    ],
  },
  {
    infinitive: "erreichen",
    russian: "достигать",
    level: "B1",
    type: "weak",
    forms: [
      "erreiche",
      "erreichst",
      "erreicht",
      "erreichen",
      "erreicht",
      "erreichen",
    ],
  },
  {
    infinitive: "erwarten",
    russian: "ожидать",
    level: "B1",
    type: "weak",
    forms: [
      "erwarte",
      "erwartest",
      "erwartet",
      "erwarten",
      "erwartet",
      "erwarten",
    ],
  },
  {
    infinitive: "empfehlen",
    russian: "рекомендовать",
    level: "B1",
    type: "strong",
    forms: [
      "empfehle",
      "empfiehlst",
      "empfiehlt",
      "empfehlen",
      "empfehlt",
      "empfehlen",
    ],
  },
  {
    infinitive: "genießen",
    russian: "наслаждаться",
    level: "B1",
    type: "strong",
    forms: ["genieße", "genießt", "genießt", "genießen", "genießt", "genießen"],
  },
  {
    infinitive: "heiraten",
    russian: "жениться",
    level: "B1",
    type: "weak",
    forms: [
      "heirate",
      "heiratest",
      "heiratet",
      "heiraten",
      "heiratet",
      "heiraten",
    ],
  },
  {
    infinitive: "informieren",
    russian: "информировать",
    level: "B1",
    type: "weak",
    forms: [
      "informiere",
      "informierst",
      "informiert",
      "informieren",
      "informiert",
      "informieren",
    ],
  },
  {
    infinitive: "interessieren",
    russian: "интересовать",
    level: "B1",
    type: "weak",
    forms: [
      "interessiere",
      "interessierst",
      "interessiert",
      "interessieren",
      "interessiert",
      "interessieren",
    ],
  },
  {
    infinitive: "scheinen",
    russian: "светить, казаться",
    level: "B1",
    type: "strong",
    forms: [
      "scheine",
      "scheinst",
      "scheint",
      "scheinen",
      "scheint",
      "scheinen",
    ],
  },
  {
    infinitive: "teilnehmen",
    russian: "участвовать",
    level: "B1",
    type: "separable",
    forms: [
      "nehme teil",
      "nimmst teil",
      "nimmt teil",
      "nehmen teil",
      "nehmt teil",
      "nehmen teil",
    ],
  },
  {
    infinitive: "trennen",
    russian: "разделять",
    level: "B1",
    type: "weak",
    forms: ["trenne", "trennst", "trennt", "trennen", "trennt", "trennen"],
  },
  {
    infinitive: "vergleichen",
    russian: "сравнивать",
    level: "B1",
    type: "strong",
    forms: [
      "vergleiche",
      "vergleichst",
      "vergleicht",
      "vergleichen",
      "vergleicht",
      "vergleichen",
    ],
  },
  {
    infinitive: "versprechen",
    russian: "обещать",
    level: "B1",
    type: "strong",
    forms: [
      "verspreche",
      "versprichst",
      "verspricht",
      "versprechen",
      "versprecht",
      "versprechen",
    ],
  },
  {
    infinitive: "vorstellen",
    russian: "представлять",
    level: "B1",
    type: "separable",
    forms: [
      "stelle vor",
      "stellst vor",
      "stellt vor",
      "stellen vor",
      "stellt vor",
      "stellen vor",
    ],
  },
  {
    infinitive: "wachsen",
    russian: "расти",
    level: "B1",
    type: "strong",
    forms: ["wachse", "wächst", "wächst", "wachsen", "wachst", "wachsen"],
  },
  // B2
  {
    infinitive: "analysieren",
    russian: "анализировать",
    level: "B2",
    type: "weak",
    forms: [
      "analysiere",
      "analysierst",
      "analysiert",
      "analysieren",
      "analysiert",
      "analysieren",
    ],
  },
  {
    infinitive: "argumentieren",
    russian: "аргументировать",
    level: "B2",
    type: "weak",
    forms: [
      "argumentiere",
      "argumentierst",
      "argumentiert",
      "argumentieren",
      "argumentiert",
      "argumentieren",
    ],
  },
  {
    infinitive: "beachten",
    russian: "обращать внимание",
    level: "B2",
    type: "weak",
    forms: [
      "beachte",
      "beachtest",
      "beachtet",
      "beachten",
      "beachtet",
      "beachten",
    ],
  },
  {
    infinitive: "behaupten",
    russian: "утверждать",
    level: "B2",
    type: "weak",
    forms: [
      "behaupte",
      "behauptest",
      "behauptet",
      "behaupten",
      "behauptet",
      "behaupten",
    ],
  },
  {
    infinitive: "beitragen",
    russian: "вносить вклад",
    level: "B2",
    type: "separable",
    forms: [
      "trage bei",
      "trägst bei",
      "trägt bei",
      "tragen bei",
      "tragt bei",
      "tragen bei",
    ],
  },
  {
    infinitive: "beschließen",
    russian: "решать, принимать решение",
    level: "B2",
    type: "strong",
    forms: [
      "beschließe",
      "beschließt",
      "beschließt",
      "beschließen",
      "beschließt",
      "beschließen",
    ],
  },
  {
    infinitive: "betonen",
    russian: "подчеркивать",
    level: "B2",
    type: "weak",
    forms: ["betone", "betonst", "betont", "betonen", "betont", "betonen"],
  },
  {
    infinitive: "betrachten",
    russian: "рассматривать",
    level: "B2",
    type: "weak",
    forms: [
      "betrachte",
      "betrachtest",
      "betrachtet",
      "betrachten",
      "betrachtet",
      "betrachten",
    ],
  },
  {
    infinitive: "beweisen",
    russian: "доказывать",
    level: "B2",
    type: "strong",
    forms: ["beweise", "beweist", "beweist", "beweisen", "beweist", "beweisen"],
  },
  {
    infinitive: "darstellen",
    russian: "изображать, представлять",
    level: "B2",
    type: "separable",
    forms: [
      "stelle dar",
      "stellst dar",
      "stellt dar",
      "stellen dar",
      "stellt dar",
      "stellen dar",
    ],
  },
  {
    infinitive: "diskutieren",
    russian: "дискутировать",
    level: "B2",
    type: "weak",
    forms: [
      "diskutiere",
      "diskutierst",
      "diskutiert",
      "diskutieren",
      "diskutiert",
      "diskutieren",
    ],
  },
  {
    infinitive: "durchführen",
    russian: "проводить",
    level: "B2",
    type: "separable",
    forms: [
      "führe durch",
      "führst durch",
      "führt durch",
      "führen durch",
      "führt durch",
      "führen durch",
    ],
  },
  {
    infinitive: "ermöglichen",
    russian: "делать возможным",
    level: "B2",
    type: "weak",
    forms: [
      "ermögliche",
      "ermöglichst",
      "ermöglicht",
      "ermöglichen",
      "ermöglicht",
      "ermöglichen",
    ],
  },
  {
    infinitive: "erwägen",
    russian: "обдумывать",
    level: "B2",
    type: "strong",
    forms: ["erwäge", "erwägst", "erwägt", "erwägen", "erwägt", "erwägen"],
  },
  {
    infinitive: "feststellen",
    russian: "устанавливать, констатировать",
    level: "B2",
    type: "separable",
    forms: [
      "stelle fest",
      "stellst fest",
      "stellt fest",
      "stellen fest",
      "stellt fest",
      "stellen fest",
    ],
  },
  {
    infinitive: "fördern",
    russian: "способствовать",
    level: "B2",
    type: "weak",
    forms: ["fördere", "förderst", "fördert", "fördern", "fördert", "fördern"],
  },
  {
    infinitive: "kritisieren",
    russian: "критиковать",
    level: "B2",
    type: "weak",
    forms: [
      "kritisiere",
      "kritisierst",
      "kritisiert",
      "kritisieren",
      "kritisiert",
      "kritisieren",
    ],
  },
  {
    infinitive: "lösen",
    russian: "решать (проблему)",
    level: "B2",
    type: "weak",
    forms: ["löse", "löst", "löst", "lösen", "löst", "lösen"],
  },
  {
    infinitive: "schützen",
    russian: "защищать",
    level: "B2",
    type: "weak",
    forms: ["schütze", "schützt", "schützt", "schützen", "schützt", "schützen"],
  },
  {
    infinitive: "überzeugen",
    russian: "убеждать",
    level: "B2",
    type: "weak",
    forms: [
      "überzeuge",
      "überzeugst",
      "überzeugt",
      "überzeugen",
      "überzeugt",
      "überzeugen",
    ],
  },
  {
    infinitive: "umsetzen",
    russian: "реализовывать",
    level: "B2",
    type: "separable",
    forms: [
      "setze um",
      "setzt um",
      "setzt um",
      "setzen um",
      "setzt um",
      "setzen um",
    ],
  },
  {
    infinitive: "unterscheiden",
    russian: "различать",
    level: "B2",
    type: "strong",
    forms: [
      "unterscheide",
      "unterscheidest",
      "unterscheidet",
      "unterscheiden",
      "unterscheidet",
      "unterscheiden",
    ],
  },
  {
    infinitive: "unterstützen",
    russian: "поддерживать",
    level: "B2",
    type: "weak",
    forms: [
      "unterstütze",
      "unterstützt",
      "unterstützt",
      "unterstützen",
      "unterstützt",
      "unterstützen",
    ],
  },
  {
    infinitive: "verursachen",
    russian: "быть причиной",
    level: "B2",
    type: "weak",
    forms: [
      "verursache",
      "verursachst",
      "verursacht",
      "verursachen",
      "verursacht",
      "verursachen",
    ],
  },
  {
    infinitive: "vorschlagen",
    russian: "предлагать",
    level: "B2",
    type: "separable",
    forms: [
      "schlage vor",
      "schlägst vor",
      "schlägt vor",
      "schlagen vor",
      "schlagt vor",
      "schlagen vor",
    ],
  },
  {
    infinitive: "wahrnehmen",
    russian: "воспринимать",
    level: "B2",
    type: "separable",
    forms: [
      "nehme wahr",
      "nimmst wahr",
      "nimmt wahr",
      "nehmen wahr",
      "nehmt wahr",
      "nehmen wahr",
    ],
  },
  {
    infinitive: "warnen",
    russian: "предупреждать",
    level: "B2",
    type: "weak",
    forms: ["warne", "warnst", "warnt", "warnen", "warnt", "warnen"],
  },
  {
    infinitive: "zusammenfassen",
    russian: "обобщать, подводить итог",
    level: "B2",
    type: "separable",
    forms: [
      "fasse zusammen",
      "fasst zusammen",
      "fasst zusammen",
      "fassen zusammen",
      "fasst zusammen",
      "fassen zusammen",
    ],
  },
  {
    infinitive: "zweifeln",
    russian: "сомневаться",
    level: "B2",
    type: "weak",
    forms: [
      "zweifle",
      "zweifelst",
      "zweifelt",
      "zweifeln",
      "zweifelt",
      "zweifeln",
    ],
  },
];
