// Этот файл теперь хранит все глаголы.
// Если вы захотите добавить новые, вы будете редактировать только этот файл.

export const allVerbs = [
    // A1
    { infinitive: 'sein', russian: 'быть', level: 'A1', forms: ['bin', 'bist', 'ist', 'ist', 'ist', 'sind', 'seid', 'sind', 'sind'] },
    { infinitive: 'haben', russian: 'иметь', level: 'A1', forms: ['habe', 'hast', 'hat', 'hat', 'hat', 'haben', 'habt', 'haben', 'haben'] },
    { infinitive: 'werden', russian: 'становиться', level: 'A1', forms: ['werde', 'wirst', 'wird', 'wird', 'wird', 'werden', 'werdet', 'werden', 'werden'] },
    { infinitive: 'können', russian: 'мочь', level: 'A1', forms: ['kann', 'kannst', 'kann', 'kann', 'kann', 'können', 'könnt', 'können', 'können'] },
    { infinitive: 'müssen', russian: 'быть должным', level: 'A1', forms: ['muss', 'musst', 'muss', 'muss', 'muss', 'müssen', 'müsst', 'müssen', 'müssen'] },
    { infinitive: 'wollen', russian: 'хотеть', level: 'A1', forms: ['will', 'willst', 'will', 'will', 'will', 'wollen', 'wollt', 'wollen', 'wollen'] },
    { infinitive: 'sagen', russian: 'сказать', level: 'A1', forms: ['sage', 'sagst', 'sagt', 'sagt', 'sagt', 'sagen', 'sagt', 'sagen', 'sagen'] },
    { infinitive: 'machen', russian: 'делать', level: 'A1', forms: ['mache', 'machst', 'macht', 'macht', 'macht', 'machen', 'macht', 'machen', 'machen'] },
    { infinitive: 'geben', russian: 'давать', level: 'A1', forms: ['gebe', 'gibst', 'gibt', 'gibt', 'gibt', 'geben', 'gebt', 'geben', 'geben'] },
    { infinitive: 'kommen', russian: 'приходить', level: 'A1', forms: ['komme', 'kommst', 'kommt', 'kommt', 'kommt', 'kommen', 'kommt', 'kommen', 'kommen'] },
    { infinitive: 'gehen', russian: 'идти', level: 'A1', forms: ['gehe', 'gehst', 'geht', 'geht', 'geht', 'gehen', 'geht', 'gehen', 'gehen'] },
    { infinitive: 'wissen', russian: 'знать', level: 'A1', forms: ['weiß', 'weißt', 'weiß', 'weiß', 'weiß', 'wissen', 'wisst', 'wissen', 'wissen'] },
    { infinitive: 'sehen', russian: 'видеть', level: 'A1', forms: ['sehe', 'siehst', 'sieht', 'sieht', 'sieht', 'sehen', 'seht', 'sehen', 'sehen'] },
    { infinitive: 'finden', russian: 'находить', level: 'A1', forms: ['finde', 'findest', 'findet', 'findet', 'findet', 'finden', 'findet', 'finden', 'finden'] },
    { infinitive: 'bleiben', russian: 'оставаться', level: 'A1', forms: ['bleibe', 'bleibst', 'bleibt', 'bleibt', 'bleibt', 'bleiben', 'bleibt', 'bleiben', 'bleiben'] },
    { infinitive: 'heißen', russian: 'называться', level: 'A1', forms: ['heiße', 'heißt', 'heißt', 'heißt', 'heißt', 'heißen', 'heißt', 'heißen', 'heißen'] },
    { infinitive: 'denken', russian: 'думать', level: 'A1', forms: ['denke', 'denkst', 'denkt', 'denkt', 'denkt', 'denken', 'denkt', 'denken', 'denken'] },
    { infinitive: 'nehmen', russian: 'брать', level: 'A1', forms: ['nehme', 'nimmst', 'nimmt', 'nimmt', 'nimmt', 'nehmen', 'nehmt', 'nehmen', 'nehmen'] },
    { infinitive: 'tun', russian: 'делать', level: 'A1', forms: ['tue', 'tust', 'tut', 'tut', 'tut', 'tun', 'tut', 'tun', 'tun'] },
    { infinitive: 'sprechen', russian: 'говорить', level: 'A1', forms: ['spreche', 'sprichst', 'spricht', 'spricht', 'spricht', 'sprechen', 'sprecht', 'sprechen', 'sprechen'] },
    { infinitive: 'fahren', russian: 'ехать', level: 'A1', forms: ['fahre', 'fährst', 'fährt', 'fährt', 'fährt', 'fahren', 'fahrt', 'fahren', 'fahren'] },
    { infinitive: 'fragen', russian: 'спрашивать', level: 'A1', forms: ['frage', 'fragst', 'fragt', 'fragt', 'fragt', 'fragen', 'fragt', 'fragen', 'fragen'] },
    { infinitive: 'arbeiten', russian: 'работать', level: 'A1', forms: ['arbeite', 'arbeitest', 'arbeitet', 'arbeitet', 'arbeitet', 'arbeiten', 'arbeitet', 'arbeiten', 'arbeiten'] },
    { infinitive: 'brauchen', russian: 'нуждаться', level: 'A1', forms: ['brauche', 'brauchst', 'braucht', 'braucht', 'braucht', 'brauchen', 'braucht', 'brauchen', 'brauchen'] },
    { infinitive: 'glauben', russian: 'верить', level: 'A1', forms: ['glaube', 'glaubst', 'glaubt', 'glaubt', 'glaubt', 'glauben', 'glaubt', 'glauben', 'glauben'] },
    { infinitive: 'helfen', russian: 'помогать', level: 'A1', forms: ['helfe', 'hilfst', 'hilft', 'hilft', 'hilft', 'helfen', 'helft', 'helfen', 'helfen'] },
    { infinitive: 'kaufen', russian: 'покупать', level: 'A1', forms: ['kaufe', 'kaufst', 'kauft', 'kauft', 'kauft', 'kaufen', 'kauft', 'kaufen', 'kaufen'] },
    { infinitive: 'lernen', russian: 'учиться', level: 'A1', forms: ['lerne', 'lernst', 'lernt', 'lernt', 'lernt', 'lernen', 'lernt', 'lernen', 'lernen'] },
    { infinitive: 'lesen', russian: 'читать', level: 'A1', forms: ['lese', 'liest', 'liest', 'liest', 'liest', 'lesen', 'lest', 'lesen', 'lesen'] },
    { infinitive: 'schlafen', russian: 'спать', level: 'A1', forms: ['schlafe', 'schläfst', 'schläft', 'schläft', 'schläft', 'schlafen', 'schlaft', 'schlafen', 'schlafen'] },
    { infinitive: 'schreiben', russian: 'писать', level: 'A1', forms: ['schreibe', 'schreibst', 'schreibt', 'schreibt', 'schreibt', 'schreiben', 'schreibt', 'schreiben', 'schreiben'] },
    { infinitive: 'spielen', russian: 'играть', level: 'A1', forms: ['spiele', 'spielst', 'spielt', 'spielt', 'spielt', 'spielen', 'spielt', 'spielen', 'spielen'] },
    { infinitive: 'trinken', russian: 'пить', level: 'A1', forms: ['trinke', 'trinkst', 'trinkt', 'trinkt', 'trinkt', 'trinken', 'trinkt', 'trinken', 'trinken'] },
    { infinitive: 'wohnen', russian: 'проживать', level: 'A1', forms: ['wohne', 'wohnst', 'wohnt', 'wohnt', 'wohnt', 'wohnen', 'wohnt', 'wohnen', 'wohnen'] },
    { infinitive: 'zeigen', russian: 'показывать', level: 'A1', forms: ['zeige', 'zeigst', 'zeigt', 'zeigt', 'zeigt', 'zeigen', 'zeigt', 'zeigen', 'zeigen'] },
    // A2
    { infinitive: 'anrufen', russian: 'звонить по телефону', level: 'A2', forms: ['rufe an', 'rufst an', 'ruft an', 'ruft an', 'ruft an', 'rufen an', 'ruft an', 'rufen an', 'rufen an'] },
    { infinitive: 'beginnen', russian: 'начинать', level: 'A2', forms: ['beginne', 'beginnst', 'beginnt', 'beginnt', 'beginnt', 'beginnen', 'beginnt', 'beginnen', 'beginnen'] },
    { infinitive: 'bekommen', russian: 'получать', level: 'A2', forms: ['bekomme', 'bekommst', 'bekommt', 'bekommt', 'bekommt', 'bekommen', 'bekommt', 'bekommen', 'bekommen'] },
    { infinitive: 'bestellen', russian: 'заказывать', level: 'A2', forms: ['bestelle', 'bestellst', 'bestellt', 'bestellt', 'bestellt', 'bestellen', 'bestellt', 'bestellen', 'bestellen'] },
    { infinitive: 'bezahlen', russian: 'платить', level: 'A2', forms: ['bezahle', 'bezahlst', 'bezahlt', 'bezahlt', 'bezahlt', 'bezahlen', 'bezahlt', 'bezahlen', 'bezahlen'] },
    { infinitive: 'bitten', russian: 'просить', level: 'A2', forms: ['bitte', 'bittest', 'bittet', 'bittet', 'bittet', 'bitten', 'bittet', 'bitten', 'bitten'] },
    { infinitive: 'danken', russian: 'благодарить', level: 'A2', forms: ['danke', 'dankst', 'dankt', 'dankt', 'dankt', 'danken', 'dankt', 'danken', 'danken'] },
    { infinitive: 'einladen', russian: 'приглашать', level: 'A2', forms: ['lade ein', 'lädst ein', 'lädt ein', 'lädt ein', 'lädt ein', 'laden ein', 'ladet ein', 'laden ein', 'laden ein'] },
    { infinitive: 'erzählen', russian: 'рассказывать', level: 'A2', forms: ['erzähle', 'erzählst', 'erzählt', 'erzählt', 'erzählt', 'erzählen', 'erzählt', 'erzählen', 'erzählen'] },
    { infinitive: 'essen', russian: 'есть, кушать', level: 'A2', forms: ['esse', 'isst', 'isst', 'isst', 'isst', 'essen', 'esst', 'essen', 'essen'] },
    { infinitive: 'feiern', russian: 'праздновать', level: 'A2', forms: ['feiere', 'feierst', 'feiert', 'feiert', 'feiert', 'feiern', 'feiert', 'feiern', 'feiern'] },
    { infinitive: 'gefallen', russian: 'нравиться', level: 'A2', forms: ['gefalle', 'gefällst', 'gefällt', 'gefällt', 'gefällt', 'gefallen', 'gefallt', 'gefallen', 'gefallen'] },
    { infinitive: 'gehören', russian: 'принадлежать', level: 'A2', forms: ['gehöre', 'gehörst', 'gehört', 'gehört', 'gehört', 'gehören', 'gehört', 'gehören', 'gehören'] },
    { infinitive: 'gewinnen', russian: 'выигрывать', level: 'A2', forms: ['gewinne', 'gewinnst', 'gewinnt', 'gewinnt', 'gewinnt', 'gewinnen', 'gewinnt', 'gewinnen', 'gewinnen'] },
    { infinitive: 'hoffen', russian: 'надеяться', level: 'A2', forms: ['hoffe', 'hoffst', 'hofft', 'hofft', 'hofft', 'hoffen', 'hofft', 'hoffen', 'hoffen'] },
    { infinitive: 'kennenlernen', russian: 'знакомиться', level: 'A2', forms: ['lerne kennen', 'lernst kennen', 'lernt kennen', 'lernt kennen', 'lernt kennen', 'lernen kennen', 'lernt kennen', 'lernen kennen', 'lernen kennen'] },
    { infinitive: 'lachen', russian: 'смеяться', level: 'A2', forms: ['lache', 'lachst', 'lacht', 'lacht', 'lacht', 'lachen', 'lacht', 'lachen', 'lachen'] },
    { infinitive: 'laufen', russian: 'бежать', level: 'A2', forms: ['laufe', 'läufst', 'läuft', 'läuft', 'läuft', 'laufen', 'lauft', 'laufen', 'laufen'] },
    { infinitive: 'reisen', russian: 'путешествовать', level: 'A2', forms: ['reise', 'reist', 'reist', 'reist', 'reist', 'reisen', 'reist', 'reisen', 'reisen'] },
    { infinitive: 'reservieren', russian: 'резервировать', level: 'A2', forms: ['reserviere', 'reservierst', 'reserviert', 'reserviert', 'reserviert', 'reservieren', 'reserviert', 'reservieren', 'reservieren'] },
    { infinitive: 'vergessen', russian: 'забывать', level: 'A2', forms: ['vergesse', 'vergisst', 'vergisst', 'vergisst', 'vergisst', 'vergessen', 'vergesst', 'vergessen', 'vergessen'] },
    { infinitive: 'verlieren', russian: 'терять', level: 'A2', forms: ['verliere', 'verlierst', 'verliert', 'verliert', 'verliert', 'verlieren', 'verliert', 'verlieren', 'verlieren'] },
    { infinitive: 'verstehen', russian: 'понимать', level: 'A2', forms: ['verstehe', 'verstehst', 'versteht', 'versteht', 'versteht', 'verstehen', 'versteht', 'verstehen', 'verstehen'] },
    { infinitive: 'vorbereiten', russian: 'готовиться', level: 'A2', forms: ['bereite vor', 'bereitest vor', 'bereitet vor', 'bereitet vor', 'bereitet vor', 'bereiten vor', 'bereitet vor', 'bereiten vor', 'bereiten vor'] },
    { infinitive: 'warten', russian: 'ждать', level: 'A2', forms: ['warte', 'wartest', 'wartet', 'wartet', 'wartet', 'warten', 'wartet', 'warten', 'warten'] },
    // B1
    { infinitive: 'abhängen', russian: 'зависеть', level: 'B1', forms: ['hänge ab', 'hängst ab', 'hängt ab', 'hängt ab', 'hängt ab', 'hängen ab', 'hängt ab', 'hängen ab', 'hängen ab'] },
    { infinitive: 'anbieten', russian: 'предлагать', level: 'B1', forms: ['biete an', 'bietest an', 'bietet an', 'bietet an', 'bietet an', 'bieten an', 'bietet an', 'bieten an', 'bieten an'] },
    { infinitive: 'annehmen', russian: 'принимать', level: 'B1', forms: ['nehme an', 'nimmst an', 'nimmt an', 'nimmt an', 'nimmt an', 'nehmen an', 'nehmt an', 'nehmen an', 'nehmen an'] },
    { infinitive: 'benutzen', russian: 'использовать', level: 'B1', forms: ['benutze', 'benutzt', 'benutzt', 'benutzt', 'benutzt', 'benutzen', 'benutzt', 'benutzen', 'benutzen'] },
    { infinitive: 'beraten', russian: 'советовать', level: 'B1', forms: ['berate', 'berätst', 'berät', 'berät', 'berät', 'beraten', 'beratet', 'beraten', 'beraten'] },
    { infinitive: 'entscheiden', russian: 'решать', level: 'B1', forms: ['entscheide', 'entscheidest', 'entscheidet', 'entscheidet', 'entscheidet', 'entscheiden', 'entscheidet', 'entscheiden', 'entscheiden'] },
    { infinitive: 'erinnern', russian: 'помнить', level: 'B1', forms: ['erinnere', 'erinnerst', 'erinnert', 'erinnert', 'erinnert', 'erinnern', 'erinnert', 'erinnern', 'erinnern'] },
    { infinitive: 'erlauben', russian: 'разрешать', level: 'B1', forms: ['erlaube', 'erlaubst', 'erlaubt', 'erlaubt', 'erlaubt', 'erlauben', 'erlaubt', 'erlauben', 'erlauben'] },
    { infinitive: 'erreichen', russian: 'достигать', level: 'B1', forms: ['erreiche', 'erreichst', 'erreicht', 'erreicht', 'erreicht', 'erreichen', 'erreicht', 'erreichen', 'erreichen'] },
    { infinitive: 'empfehlen', russian: 'рекомендовать', level: 'B1', forms: ['empfehle', 'empfiehlst', 'empfiehlt', 'empfiehlt', 'empfiehlt', 'empfehlen', 'empfehlt', 'empfehlen', 'empfehlen'] },
    { infinitive: 'genießen', russian: 'наслаждаться', level: 'B1', forms: ['genieße', 'genießt', 'genießt', 'genießt', 'genießt', 'genießen', 'genießt', 'genießen', 'genießen'] },
    { infinitive: 'heiraten', russian: 'жениться', level: 'B1', forms: ['heirate', 'heiratest', 'heiratet', 'heiratet', 'heiratet', 'heiraten', 'heiratet', 'heiraten', 'heiraten'] },
    { infinitive: 'informieren', russian: 'информировать', level: 'B1', forms: ['informiere', 'informierst', 'informiert', 'informiert', 'informiert', 'informieren', 'informiert', 'informieren', 'informieren'] },
    { infinitive: 'interessieren', russian: 'интересовать', level: 'B1', forms: ['interessiere', 'interessierst', 'interessiert', 'interessiert', 'interessiert', 'interessieren', 'interessiert', 'interessieren', 'interessieren'] },
    { infinitive: 'teilnehmen', russian: 'участвовать', level: 'B1', forms: ['nehme teil', 'nimmst teil', 'nimmt teil', 'nimmt teil', 'nimmt teil', 'nehmen teil', 'nehmt teil', 'nehmen teil', 'nehmen teil'] },
    { infinitive: 'vergleichen', russian: 'сравнивать', level: 'B1', forms: ['vergleiche', 'vergleichst', 'vergleicht', 'vergleicht', 'vergleicht', 'vergleichen', 'vergleicht', 'vergleichen', 'vergleichen'] },
    { infinitive: 'versprechen', russian: 'обещать', level: 'B1', forms: ['verspreche', 'versprichst', 'verspricht', 'verspricht', 'verspricht', 'versprechen', 'versprecht', 'versprechen', 'versprechen'] },
    { infinitive: 'vorstellen', russian: 'представлять', level: 'B1', forms: ['stelle vor', 'stellst vor', 'stellt vor', 'stellt vor', 'stellt vor', 'stellen vor', 'stellt vor', 'stellen vor', 'stellen vor'] },
    { infinitive: 'wachsen', russian: 'расти', level: 'B1', forms: ['wachse', 'wächst', 'wächst', 'wächst', 'wächst', 'wachsen', 'wachst', 'wachsen', 'wachsen'] },
    // B2
    { infinitive: 'analysieren', russian: 'анализировать', level: 'B2', forms: ['analysiere', 'analysierst', 'analysiert', 'analysiert', 'analysiert', 'analysieren', 'analysiert', 'analysieren', 'analysieren'] },
    { infinitive: 'argumentieren', russian: 'аргументировать', level: 'B2', forms: ['argumentiere', 'argumentierst', 'argumentiert', 'argumentiert', 'argumentiert', 'argumentieren', 'argumentiert', 'argumentieren', 'argumentieren'] },
    { infinitive: 'behaupten', russian: 'утверждать', level: 'B2', forms: ['behaupte', 'behauptest', 'behauptet', 'behauptet', 'behauptet', 'behaupten', 'behauptet', 'behaupten', 'behaupten'] },
    { infinitive: 'beitragen', russian: 'вносить вклад', level: 'B2', forms: ['trage bei', 'trägst bei', 'trägt bei', 'trägt bei', 'trägt bei', 'tragen bei', 'tragt bei', 'tragen bei', 'tragen bei'] },
    { infinitive: 'betrachten', russian: 'рассматривать', level: 'B2', forms: ['betrachte', 'betrachtest', 'betrachtet', 'betrachtet', 'betrachtet', 'betrachten', 'betrachtet', 'betrachten', 'betrachten'] },
    { infinitive: 'beweisen', russian: 'доказывать', level: 'B2', forms: ['beweise', 'beweist', 'beweist', 'beweist', 'beweist', 'beweisen', 'beweist', 'beweisen', 'beweisen'] },
    { infinitive: 'diskutieren', russian: 'дискутировать', level: 'B2', forms: ['diskutiere', 'diskutierst', 'diskutiert', 'diskutiert', 'diskutiert', 'diskutieren', 'diskutiert', 'diskutieren', 'diskutieren'] },
    { infinitive: 'durchführen', russian: 'проводить', level: 'B2', forms: ['führe durch', 'führst durch', 'führt durch', 'führt durch', 'führt durch', 'führen durch', 'führt durch', 'führen durch', 'führen durch'] },
    { infinitive: 'erwägen', russian: 'обдумывать', level: 'B2', forms: ['erwäge', 'erwägst', 'erwägt', 'erwägt', 'erwägt', 'erwägen', 'erwägt', 'erwägen', 'erwägen'] },
    { infinitive: 'fördern', russian: 'способствовать', level: 'B2', forms: ['fördere', 'förderst', 'fördert', 'fördert', 'fördert', 'fördern', 'fördert', 'fördern', 'fördern'] },
    { infinitive: 'kritisieren', russian: 'критиковать', level: 'B2', forms: ['kritisiere', 'kritisierst', 'kritisiert', 'kritisiert', 'kritisiert', 'kritisieren', 'kritisiert', 'kritisieren', 'kritisieren'] },
    { infinitive: 'lösen', russian: 'решать (проблему)', level: 'B2', forms: ['löse', 'löst', 'löst', 'löst', 'löst', 'lösen', 'löst', 'lösen', 'lösen'] },
    { infinitive: 'schützen', russian: 'защищать', level: 'B2', forms: ['schütze', 'schützt', 'schützt', 'schützt', 'schützt', 'schützen', 'schützt', 'schützen', 'schützen'] },
    { infinitive: 'überzeugen', russian: 'убеждать', level: 'B2', forms: ['überzeuge', 'überzeugst', 'überzeugt', 'überzeugt', 'überzeugt', 'überzeugen', 'überzeugt', 'überzeugen', 'überzeugen'] },
    { infinitive: 'unterstützen', russian: 'поддерживать', level: 'B2', forms: ['unterstütze', 'unterstützt', 'unterstützt', 'unterstützt', 'unterstützt', 'unterstützen', 'unterstützt', 'unterstützen', 'unterstützen'] },
    { infinitive: 'verursachen', russian: 'быть причиной', level: 'B2', forms: ['verursache', 'verursachst', 'verursacht', 'verursacht', 'verursacht', 'verursachen', 'verursacht', 'verursachen', 'verursachen'] },
    { infinitive: 'vorschlagen', russian: 'предлагать', level: 'B2', forms: ['schlage vor', 'schlägst vor', 'schlägt vor', 'schlägt vor', 'schlägt vor', 'schlagen vor', 'schlagt vor', 'schlagen vor', 'schlagen vor'] },
    { infinitive: 'warnen', russian: 'предупреждать', level: 'B2', forms: ['warne', 'warnst', 'warnt', 'warnt', 'warnt', 'warnen', 'warnt', 'warnen', 'warnen'] },
    { infinitive: 'zweifeln', russian: 'сомневаться', level: 'B2', forms: ['zweifle', 'zweifelst', 'zweifelt', 'zweifelt', 'zweifelt', 'zweifeln', 'zweifelt', 'zweifeln', 'zweifeln'] },
];
